modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mobpacified"
version="1.0"
displayName="Mob Pacified Mobs"
authors="Gabriel"
description='''Allows players to tame hostile mobs using a nametag called "Amigao".'''

[[dependencies.mobpacified]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.mobpacified]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"